---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[ftp-cloudfs::default]
    attributes: {
    	"ftp-cloudfs": {
    		"auth_url": "http://test/url",
    		"bind_address": "127.0.0.1",
    		"memcached": true,
    		"syslog": "yes",
    		"split_large_files": "5000",
    		"hide_part_dir": "yes",
    		"keystone-auth": true,
    		"keystone_region_name": "region1",
    		"verbose": "yes"
    	}
    }
