language: ruby
cache: bundler
gemfile:
  - Gemfile
rvm:
  - 1.9.3
  - 2.0.0
bundler_args: --without kitchen
before_script:
  - bundle exec berks install
script:
  - bundle exec strainer test --except kitchen
  - bundle exec rake knife